### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by matfallet** [CBI-PITT/napari-imaris-loader#8]
Dear developper, 

I am very interested by your imaris loader, nevertheless, I did'nt sucess to install it.
I have installed the imaris loader on my napari env (windows), On my napari env, I then launch napari. 

When I try to open an ims file with the open function of napari, it doesn't work, any idea of the problem ?

11:00:40 ERROR PluginError: Error in plugin 'builtins', hook 'napari_get_reader'
  Cause was: ValueError('Could not load "" \nReason: "cannot find loader for this HDF5 file"\nPlease see documentation at: http://pillow.readthedocs.io/en/latest/installation.html#external-libraries')
    in file: C:\Users\mathi\anaconda3\envs\napari-env\lib\site-packages\imageio\plugins\pillow.py
    at line: 680
     author: napari team
      email: [napari-steering-council@googlegroups.com](mailto:napari-steering-council@googlegroups.com)
    package: napari
        url: https://napari.org/
    version: 0.4.0

**Comment by AlanMWatson** [comment]
This error seems to be due to the environment not being able to find a HDF5 reader with is implemented by h5py in 'imaris-ims-file-reader' used by the napari reader.  Make sure h5py is installed (although this should have happened automatically).  There may be a conflict.

The best chance of success is to install a in a new environment.  The easiest way to do this using conda for env management is as below.  I just verified on windows and linux that this is working.  Please let me know if you are succesful.  Thanks!

conda create -n napari_imaris python=3.8
pip install napari-imaris-loader

**Comment by matfallet** [comment]
ok thanks I will do it now.  I have also encounter some problems if I try to install different plugins like czi (zeiss) et ims (and some others like video)  loader, I have this message when I try to open ims image :

"axes don't match array"

previoulsy the ims loader worked on this napari env (an other one I have with cellpose)

thanks,
Mathieu

________________________________
De : Alan Watson ***@***.***>
Envoyé : mercredi 13 avril 2022 20:06:25
À : CBI-PITT/napari-imaris-loader
Cc : Mathieu FALLET; Author
Objet : Re: [CBI-PITT/napari-imaris-loader] installation problem (Issue #8)


This error seems to be due to the environment not being able to find a HDF5 reader with is implemented by h5py in 'imaris-ims-file-reader' used by the napari reader. Make sure h5py is installed (although this should have happened automatically). There may be a conflict.

The best chance of success is to install a in a new environment. The easiest way to do this using conda for env management is as below. I just verified on windows and linux that this is working. Please let me know if you are succesful. Thanks!

conda create -n napari_imaris python=3.8
pip install napari-imaris-loader
